### ISSUE TITLE
Update to 1.8.0

### ISSUE THREAD

**Issue by Jan-E** [winlibs/libssh2#1]
@weltling 

Daniel Stenberg in gmane.network.ssh.libssh2.devel (Tue, 25 Oct 2016 08:52:48 +0200 (CEST)):

> Hi friends,
> 
> I've just packaged, signed and uploaded libssh2 1.8.0. Enjoy! As always, 
> you'll find it here:
> 
>    https://www.libssh2.org/
> 
> libssh2 1.8.0
> 
> This release includes the following changes:
> 
>   o added a basic dockerised test suite
>   o crypto: add support for the mbedTLS backend
> 
> This release includes the following bugfixes:
> 
>   o libgcrypt: fixed a NULL pointer dereference on OOM
>   o VMS: can't use %zd for off_t format
>   o VMS: update vms/libssh2_config.h
>   o windows: link with crypt32.lib
>   o libssh2_channel_open: speeling error fixed in channel error message
>   o msvc: fixed 14 compilation warnings
>   o tests: HAVE_NETINET_IN_H was not defined correctly
>   o openssl: add OpenSSL 1.1.0 compatibility
>   o cmake: Add CLEAR_MEMORY option, analogously to that for autoconf
>   o configure: make the --with-\* options override the OpenSSL default
>   o libssh2_wait_socket: set err_msg on errors
>   o libssh2_wait_socket: Fix comparison with api_timeout to use milliseconds
> 
> This release would not have looked like this without help, code, reports and
> advice from friends like these:
> 
>    Alexander Lamaison, Antenore Gatta, Brad Harder, Charles Collicutt,
>    Craig A. Berry, Dan Fandrich, Daniel Stenberg, Kamil Dudka, Keno Fischer,
>    Taylor Holberton, Viktor Szakats, Will Cosgrove, Zenju
>    (12 contributors)
> 
> ```
>      Thanks! (and sorry if I forgot to mention someone)
> ```
> ## 
> 
>   / daniel.haxx.se
> ---
> 
> libssh2-devel https://cool.haxx.se/cgi-bin/mailman/listinfo/libssh2-devel

**Comment by weltling** [comment]
Yeah, it was actually done as a dep for libcurl last time. Forgot to touch this one.

Thanks.

**Comment by Jan-E** [comment]
Never mind. BTW: libpng can be upgraded painlessly to 1.6.25, but I had troubles with 1.6.26. I do not remember the exact error messages, but maybe you can give it a try (if time permits).

**Comment by weltling** [comment]
Probably not this year anymore, except there's some security issue. Currently it's good time to freeze with regard to the upcoming 7.1 GA.

Thanks.
